import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "./context/sidebarContext";
import ThemeContextProvider from "./context/themeContext";
import { DropdownProvider } from "./context/UseDropDown";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} dark:bg-black`}>
        <DropdownProvider>
          <ThemeContextProvider>
            <SidebarProvider>{children}</SidebarProvider>
          </ThemeContextProvider>
        </DropdownProvider>
      </body>
    </html>
  );
}
